### ISSUE TITLE
Implement projects

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/laurabeatris.com#11]
## Description

Implement projects list

## Tasks

- [x] Show tooltip saying to click on the project in order to see more details about it 
- [x] Implement project list without fetching data from CMS
- [x] Modify Project component to use Image component from Next to avoid flickering of content
- [x] Implement project modal
- [x] Fetch projects from CMS on build time 

## Notes 

Define a max-height and truncate the description. When clicking on the project, should open a modal with an images carousel and the entire description being show
