### ISSUE TITLE
Implement timeline

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/laurabeatris.com#14]
## Description 

Implement a timeline to show career and life achievements. 

## Tasks 

- [x] Create `Timeline` model at GraphCMS
- [x] Create content for `Timeline` model 
- [x] Implement Timeline component (Doesn't need to connect elements for now)
- [x] Connect timeline elements for each year

## Notes 

`Timeline` Model:
```
{ 
  year: 2002,
  achievements: [{ title: 'A title', description: 'A description' }]
}
```

![image](https://user-images.githubusercontent.com/48022589/105701557-3ab0fa80-5ee9-11eb-977c-1becfea46f14.png)
