### ISSUE TITLE
Implement about page

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/laurabeatris.com#16]
## Description

Implement about page

![image](https://user-images.githubusercontent.com/48022589/105728472-f3d3fc80-5f0a-11eb-8d52-1d44b0bc22c9.png)

## Tasks

- [x] Show `About my life` section
- [x] Show `Hobbies` section
- [x] Show `Programming Journey` section
