### ISSUE TITLE
Configure SEO

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/laurabeatris.com#2]
## Description

Configure SEO by using the [next-seo](https://github.com/garmeeh/next-seo) library 

## Tasks 

- [x] Add title
- [x] Add manifest
- [x] Add favicons, touch icons and tile icons 
- [x] Generate sitemap 
- [x] Add `robots.tsx`
- [x] Configure [next-seo](https://github.com/garmeeh/next-seo)
