### ISSUE TITLE
Implement learning journal page

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/laurabeatris.com#22]
## Description 

Implement a learning journal page to document my learning journey

## Tasks 

- [x] Implement `LearningJournal` model at GraphCMS
- [x] Implement content of `LearningJournal` at GraphCMS
- [x] List `LearningJournal` results

## Notes

`LearningJourneyEntry` model:

```
{
  
  date: Date,
  work: Array<string>;
  curiosity: Array<string>;
  programming: Array<string>;
}
```
