### ISSUE TITLE
Implement project filters

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/laurabeatris.com#39]
## Description 

Implement project filters to improve the user experience when searching for projects with specific names or categories. 

## Tasks 
- [x] Implement `ProjectFilters` component that shows a search input & a menu with categories options 
- [x] Fetch data from the main page using SSR 
- [x] Use `useQuery` hook from `react-query` to query for projects 
- [x] Initialize projects data from server-side data
- [x] Debounce input change to not execute a lot of requests 
- [x] Show loading indicator when projects are being fetched
- [x]  Show message when no projects are found for a given filter
